pdf_extract_task:
  description: >
    Extract text, tables, and images from the provided PDF file.
    Use pdfplumber for text and table extraction, and pytesseract for OCR on images.
    Ensure all extracted information is saved in the specified directories.
  expected_output: >
    Text extracted from the PDF file saved in 'text_temp'.
    Tables extracted and saved in 'table_temp'.
    Images extracted and saved in 'image_temp'.
  agent: pdf_extract_assistant


qa_task:
  description: >
    Answering human input or human question about anything including the extracted PDF txt file 
  expected_output: >
    Answering human on terminal using any language that human is asking
  agent: qa_assistant